### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by ghost** [shas0910/protospace-35420#1]
https://protospace-35420.herokuapp.com/

**Comment by takumi0530** [comment]
@sproutVEVO さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
エラーページに遷移してしまいます。
<img width="632" alt="スクリーンショット 2021-04-22 11 14 34" src="https://user-images.githubusercontent.com/76197191/115646434-15535180-a35d-11eb-9c66-bab6abafd82e.png">

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
一覧表示にあるゆユーザー名をクリックすると、プロトタイプの詳細ページに遷移してしまいます。
<img width="407" alt="スクリーンショット 2021-04-22 11 19 39" src="https://user-images.githubusercontent.com/76197191/115646472-2734f480-a35d-11eb-95b0-836245a86d22.png">


- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
投稿していないプロトタイプも表示されています。

<img width="1146" alt="スクリーンショット 2021-04-22 11 19 09" src="https://user-images.githubusercontent.com/76197191/115646532-47fd4a00-a35d-11eb-9ab8-e44fbf70cd49.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by takumi0530** [comment]
@sproutVEVO さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
